#define EXS_NEED_FLOAT 0
/* exsecutor: reach backend */
/* Generated by exsc --emitte c. Do not edit: the text of this prologue is a
 * function of exsc's own bytes (docs/design/c-backend.md D5), the way the
 * reference backend's prelude blob is. */
#include <stdint.h>
#include <limits.h>
#ifndef EXS_NEED_FLOAT
#define EXS_NEED_FLOAT 1
#endif
#if EXS_NEED_FLOAT
#include <float.h>
#endif

#if !defined(__GNUC__) && !defined(__clang__)
# error "exsecutor: the emitted C is C11 plus a GCC/Clang extension set (ADR 0012)"
#endif
#if !defined(__BYTE_ORDER__) || !defined(__ORDER_LITTLE_ENDIAN__) || !defined(__ORDER_BIG_ENDIAN__)
# error "exsecutor: __BYTE_ORDER__ is required to select the nativus helpers"
#endif
#if defined(__FAST_MATH__)
# error "exsecutor: -ffast-math is refused (spec 5.4)"
#endif
#if defined(__FINITE_MATH_ONLY__) && __FINITE_MATH_ONLY__
# error "exsecutor: -ffinite-math-only is refused (spec 5.4)"
#endif

#if EXS_NEED_FLOAT
/* ---- IEEE binary32/64: the numeric subset's one target (spec 5.4) -------
 * ADR 0012's rung (b), spelled with <float.h> exactly as ADR 0012 names it
 * -- freestanding-safe, unlike __STDC_IEC_559__ (which a freestanding
 * implementation may define without honouring). `float` is binary32 and
 * `double` binary64, and no operation gains precision: FLT_EVAL_METHOD 0
 * is what makes `float op float` a FLOAT operation in C rather than a
 * double one (C's usual arithmetic conversions leave the type alone, but
 * only an evaluation method of 0 leaves the RESULT alone). Subnormals are
 * values (subnormales conservata); where C11's <float.h> stays silent
 * about them (the *_HAS_SUBNORM macros are optional before C23) the
 * runtime's MXCSR/FPCR image is what enforces it -- FTZ and DAZ clear,
 * which the reference prelude's 0x1F80 image also carries. */
_Static_assert(FLT_RADIX == 2, "exsecutor: the numeric subset is IEEE binary32/64 (spec 5.4)");
_Static_assert(FLT_MANT_DIG == 24 && DBL_MANT_DIG == 53,
               "exsecutor: float is binary32 and double is binary64");
_Static_assert(FLT_MAX_EXP == 128 && DBL_MAX_EXP == 1024,
               "exsecutor: binary32/64 exponent widths");
#if FLT_EVAL_METHOD != 0
# error "exsecutor: FLT_EVAL_METHOD must be 0 (spec 5.4: one rounding, in the operands' own width)"
#endif
#if defined(FLT_HAS_SUBNORM) && FLT_HAS_SUBNORM != 1
# error "exsecutor: float subnormals must be preserved (spec 5.4 subnormales conservata)"
#endif
#if defined(DBL_HAS_SUBNORM) && DBL_HAS_SUBNORM != 1
# error "exsecutor: double subnormals must be preserved (spec 5.4 subnormales conservata)"
#endif

/* Contraction (spec 5.4 contractio explicita; ADR 0012 problem 1). One IR
 * op is one C statement, so no emitted statement ever holds a
 * multiply-and-add tree to contract -- `fma` is the only contraction the
 * language has, it is refused by name in both backends, and this pragma is
 * the belt to that brace. `#pragma STDC FP_CONTRACT OFF` is NOT emitted:
 * measured to do nothing in both compilers, and GCC warns about it under
 * -Wall (c-backend.md D3, finding 12). Clang has nothing that works from
 * inside the source (`#pragma clang fp contract(off)` does not override a
 * command-line -ffp-contract=fast), so nothing is said to it and nothing
 * is lied about. */
#if defined(__GNUC__) && !defined(__clang__)
# pragma GCC optimize("fp-contract=off")
#endif
#endif /* EXS_NEED_FLOAT */

_Static_assert(CHAR_BIT == 8, "exsecutor: CHAR_BIT must be 8");
_Static_assert((-1 & 3) == 3, "exsecutor: two's complement");
_Static_assert(sizeof(unsigned) * CHAR_BIT >= 32, "exsecutor: unsigned holds a byte and a shift");

/* The trap hook: the ONE symbol a library-mode unit imports. Whoever links
 * it supplies the body (c-backend.md D1). Kinds are prelude/README.md's:
 * 1 numeric (overflow, a shift count past the width, a failed chk),
 * 5 terminus. */
_Noreturn void exsrt_abortus(unsigned kind);

/* Every integer value of any uN or iN is held in a uint64_t in canonical
 * form (ssa-ir.md 2.2): a uN zero-extended, an iN sign-extended. Every
 * helper assumes canonical inputs and returns a canonical result. All
 * arithmetic is on uint64_t, whose overflow C defines as modular, so no
 * emitted operation is undefined and -fwrapv / -ftrapv are irrelevant. */
static inline uint64_t exsi_mask(unsigned n)
{ return n == 64 ? UINT64_MAX : (UINT64_C(1) << n) - 1; }
static inline uint64_t exsi_norm_u(uint64_t x, unsigned n)
{ return x & exsi_mask(n); }
static inline uint64_t exsi_norm_i(uint64_t x, unsigned n)
{ uint64_t s = UINT64_C(1) << (n - 1); return ((x & exsi_mask(n)) ^ s) - s; }

#if EXS_NEED_FLOAT
/* Floats from their bits -- `fconst`'s round-trip. `fconst F bits` carries
 * the RAW bit pattern (ssa-ir.md 2.3: bits, never decimal text) and it must
 * come back exactly: payload bits included (a NaN's payload survives fneg),
 * sign included (-0.0 is a different constant from 0.0), subnormal bits
 * included (subnormales conservata). A C floating literal cannot spell any
 * of that -- a hex floating literal for an out-of-range pattern loses the
 * NaN payload and the quiet bit -- so the pattern is written as an integer
 * constant and re-read through the object representation:
 * __builtin_memcpy, the GCC-recommended bit-cast, already measured and on
 * D3's extension list for `copy n` (c-backend.md finding 13). Assumes a
 * float's byte order is the integer byte order -- true of every target in
 * scope: x86_64, riscv64 and mips64 are each uniform in their byte order,
 * which is what the emitted `exsi_ld_n` selection also assumes. */
static inline float exsi_f32_from_bits(uint32_t b)
{ float f; __builtin_memcpy(&f, &b, sizeof f); return f; }
static inline double exsi_f64_from_bits(uint64_t b)
{ double d; __builtin_memcpy(&d, &b, sizeof d); return d; }

/* The way back, for `store F`: the float's bit pattern as the integer the
 * byte-store helpers carry. Same bit-cast, same assumption a few lines
 * above (a float's byte order is the integer byte order) -- the round trip
 * store-then-load is the identity on every --hospes row, which is all
 * memory consistency asks of a bit pattern with no numeric reading. */
static inline uint32_t exsi_bits_from_f32(float f)
{ uint32_t b; __builtin_memcpy(&b, &f, sizeof b); return b; }
static inline uint64_t exsi_bits_from_f64(double d)
{ uint64_t b; __builtin_memcpy(&b, &d, sizeof b); return b; }

/* The vector float group (spec 5.4's vf32.N/vf64.N; ssa-ir.md 2.2: N lanes
 * of binary32/binary64, N in {2,4,8}), as C's vector_size extension -- one
 * of the GCC/Clang extensions ADR 0012's set already carries. One IR
 * vadd/vsub/vmul/vdiv is one C statement on the whole vector (the one
 * op-per-statement rule), and the operator's elementwise lowering is the
 * ONE IEEE rounding per lane the reference's packed addps/addpd carries:
 * GCC and Clang both lower vector_size arithmetic elementwise on x86-64
 * and soft-lower it on the mips64-none cross target, which is what keeps
 * cross=yes alive for this wave. NO intrinsics and no <emmintrin.h>-family
 * header: those spellings do not exist on the cross target. */
typedef float exs_vf32_2 __attribute__((vector_size(8)));
typedef float exs_vf32_4 __attribute__((vector_size(16)));
typedef float exs_vf32_8 __attribute__((vector_size(32)));
typedef double exs_vf64_2 __attribute__((vector_size(16)));
typedef double exs_vf64_4 __attribute__((vector_size(32)));
typedef double exs_vf64_8 __attribute__((vector_size(64)));
/* The N = 8 helpers carry 32/64-byte vectors, and both compilers note at
 * their definitions (GCC) or call sites (Clang) that passing such a vector
 * without AVX enabled "changes the ABI" (-Wpsabi). That warning is a
 * statement about TWO translation units compiled with different -m flags
 * sharing a function boundary -- and no boundary here carries a vector:
 * the helpers are `static inline` inside the single emitted unit, and the
 * unit's one imported/exported symbol (exs_initium's unsigned char *) is a
 * scalar. The note is noise for this blob and is switched off for it, the
 * way -Wno-unused-function is for the rest of it (recorded, not hidden). */
#if defined(__clang__)
# pragma clang diagnostic ignored "-Wpsabi"
#elif defined(__GNUC__)
# pragma GCC diagnostic ignored "-Wpsabi"
#endif
_Static_assert(sizeof(exs_vf32_2) == 8 && sizeof(exs_vf32_4) == 16 &&
               sizeof(exs_vf32_8) == 32,
               "exsecutor: a vf32.N is N binary32 lanes, packed (spec 5.4)");
_Static_assert(sizeof(exs_vf64_2) == 16 && sizeof(exs_vf64_4) == 32 &&
               sizeof(exs_vf64_8) == 64,
               "exsecutor: a vf64.N is N binary64 lanes, packed (spec 5.4)");

/* A vector in memory is its lanes' raw IEEE images, back to back in
 * subscript order, each element in the target's byte order -- the same
 * assumption the scalar helpers above name, so the nativus round trip is
 * the identity on every --hospes row. The load/store helpers are memcpy
 * bit baggage exactly the way the scalar float path's from_bits/bits_from
 * helpers are: no lane is read numerically on the path, so a NaN payload,
 * -0.0's sign and a subnormal's bits survive every copy (subnormales
 * conservata). */
static inline exs_vf32_2 exsi_ld_vf32_2(const unsigned char *p)
{ exs_vf32_2 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf32_4 exsi_ld_vf32_4(const unsigned char *p)
{ exs_vf32_4 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf32_8 exsi_ld_vf32_8(const unsigned char *p)
{ exs_vf32_8 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_2 exsi_ld_vf64_2(const unsigned char *p)
{ exs_vf64_2 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_4 exsi_ld_vf64_4(const unsigned char *p)
{ exs_vf64_4 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline exs_vf64_8 exsi_ld_vf64_8(const unsigned char *p)
{ exs_vf64_8 v; __builtin_memcpy(&v, p, sizeof v); return v; }
static inline void exsi_st_vf32_2(unsigned char *p, exs_vf32_2 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf32_4(unsigned char *p, exs_vf32_4 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf32_8(unsigned char *p, exs_vf32_8 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_2(unsigned char *p, exs_vf64_2 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_4(unsigned char *p, exs_vf64_4 v)
{ __builtin_memcpy(p, &v, sizeof v); }
static inline void exsi_st_vf64_8(unsigned char *p, exs_vf64_8 v)
{ __builtin_memcpy(p, &v, sizeof v); }

/* itof from a signed integer's canonical bits. The carrier holds an iN
 * sign-extended (ssa-ir.md 2.2), so the two's-complement value IS the bit
 * pattern -- but C leaves a uint64_t -> int64_t conversion that does not
 * fit IMPLEMENTATION-DEFINED, a fact this prologue asserts nowhere and
 * refuses to rely on, so the bits are re-read as int64_t exactly the way
 * fconst re-reads a pattern as a float. The signed type appears here and
 * nowhere else: this is a conversion into a float, not arithmetic, and the
 * one-op-per-statement rule keeps it out of any expression a compiler
 * could contract. */
static inline int64_t exsi_i64_from_bits(uint64_t b)
{ int64_t s; __builtin_memcpy(&s, &b, sizeof s); return s; }

#endif /* EXS_NEED_FLOAT */

static inline uint64_t exsi_add_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b;
  if (n == 64 ? t < a : t > exsi_mask(n)) exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_add_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b;
  if (n == 64 ? ((((a ^ t) & (b ^ t)) >> 63) != 0) : exsi_norm_i(t, n) != t)
    exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_sub_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b;
  if (n == 64 ? a < b : t > exsi_mask(n)) exsrt_abortus(1);
  return t; }
static inline uint64_t exsi_sub_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b;
  if (n == 64 ? ((((a ^ b) & (a ^ t)) >> 63) != 0) : exsi_norm_i(t, n) != t)
    exsrt_abortus(1);
  return t; }
/* mul checks by DIVISION at every width rather than in a wider type: GCC
 * provides __int128 only where __SIZEOF_INT128__ is defined, which excludes
 * 32-bit-pointer targets such as o64 (c-backend.md finding 5). b > M / a is
 * exact. */
static inline uint64_t exsi_mul_u(uint64_t a, uint64_t b, unsigned n)
{ if (n <= 32) { uint64_t t = a * b; if (t > exsi_mask(n)) exsrt_abortus(1); return t; }
  if (a != 0 && b > exsi_mask(n) / a) exsrt_abortus(1);
  return a * b; }
static inline uint64_t exsi_mul_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t sa = a >> 63, sb = b >> 63;
  uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;   /* magnitudes; 2^63 stays 2^63 */
  uint64_t neg = sa ^ sb;
  uint64_t lim = neg ? UINT64_C(1) << (n - 1) : (UINT64_C(1) << (n - 1)) - 1;
  if (ma != 0 && mb > lim / ma) exsrt_abortus(1);
  { uint64_t p = ma * mb; return neg ? 0 - p : p; } }   /* canonical by construction */

/* div and rem -- spec 5.4 as decided 2026-09-25: the quotient TRUNCATED
 * TOWARD ZERO and the remainder's sign FOLLOWING THE DIVIDEND, so that
 * `a == (a/b)*b + (a rem b)` holds at every pair of signs. Both trap on a
 * zero divisor, and both trap on T_MIN / -1 -- `rem` included, whose
 * mathematical value there is 0: it is the remainder OF a division that
 * does not exist, and a `rem` answering 0 where its own `div` traps would
 * falsify the identity at the one pair of operands two instructions can
 * check it on. emit.inc's __bfa_emit_divrem argues the same two paragraphs
 * for the reference; these helpers are the same function, not a second
 * opinion about it.
 *
 * THE CHECKS PRECEDE THE DIVISION, where every other trapping helper above
 * checks after, and they have to for two independent reasons. The semantic
 * one: `rem`'s result carries no trace of the overflow (T_MIN rem -1 is 0,
 * a perfectly good value of T), so there is nothing to check afterwards.
 * The harness one: every fixture is compiled `-fsanitize=undefined
 * -fno-sanitize-recover=all`, so a helper that DIVIDED first would abort
 * inside UBSan -- wrong status, wrong text, exsrt_abortus never reached --
 * on precisely the two inputs whose trap is the thing being tested.
 *
 * T_MIN IS T'S OWN, NOT INT64_MIN. In `i8`, -128 / -1 is 128, which no
 * `i8` holds, and the 64-bit division of a sign-extended -128 by -1
 * computes it without a murmur; tests/ir/trap_div_minneg1.ir is that case
 * and nothing else. So the comparison is against -2^(N-1) for the operand
 * type's own N. At N = 64 the same line also stands in for the hardware's
 * divide error, which the reference likewise turns into kind 1 rather than
 * a second signal that depends on the width.
 *
 * NO SIGNED C DIVISION ANYWHERE. The signed pair divides MAGNITUDES and
 * puts the sign back, exactly as exsi_mul_i does, so the carrier's
 * implementation-defined uint64_t -> int64_t conversion is never needed
 * (this file relies on it nowhere but exsi_i64_from_bits, and then through
 * memcpy) and UBSan's signed-overflow check is never armed. `0 - x` on a
 * uint64_t is modular C, not overflow. The magnitude of T_MIN is 2^63,
 * which `0 - a` leaves as 2^63 -- still the right unsigned magnitude.
 *
 * NO NORMALISATION, and the proof rather than the habit. With a zero
 * divisor and T_MIN / -1 excluded the result is ALREADY a value of T:
 * |a/b| <= |a| for |b| >= 1, so the only out-of-range quotient is -T_MIN,
 * which is precisely the case just excluded; and |a rem b| < |b| <=
 * 2^(N-1), in range at every sign. `0 - q` on an in-range magnitude leaves
 * the value sign-extended, which is the canonical form (ssa-ir.md 2.2).
 *
 * n IS UNUSED IN THE UNSIGNED PAIR and the parameter still stays. A uN
 * quotient is at most the dividend and a uN remainder is less than the
 * divisor, so neither can leave the type, and unsigned division has no
 * T_MIN case to exclude -- but the emitter writes ONE call shape for every
 * row of the helper table, so the argument is passed and discarded the way
 * exsi_subs_u discards it. */
static inline uint64_t exsi_div_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; if (b == 0) exsrt_abortus(1); return a / b; }
static inline uint64_t exsi_rem_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; if (b == 0) exsrt_abortus(1); return a % b; }
static inline uint64_t exsi_div_i(uint64_t a, uint64_t b, unsigned n)
{ if (b == 0) exsrt_abortus(1);
  if (a == 0 - (UINT64_C(1) << (n - 1)) && b == UINT64_MAX) exsrt_abortus(1);
  { uint64_t sa = a >> 63, sb = b >> 63;
    uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;   /* magnitudes; 2^63 stays 2^63 */
    uint64_t q = ma / mb;
    return (sa ^ sb) ? 0 - q : q; } }                    /* canonical by construction */
static inline uint64_t exsi_rem_i(uint64_t a, uint64_t b, unsigned n)
{ if (b == 0) exsrt_abortus(1);
  if (a == 0 - (UINT64_C(1) << (n - 1)) && b == UINT64_MAX) exsrt_abortus(1);
  { uint64_t sa = a >> 63, sb = b >> 63;
    uint64_t ma = sa ? 0 - a : a, mb = sb ? 0 - b : b;
    uint64_t r = ma % mb;
    return sa ? 0 - r : r; } }                           /* the DIVIDEND's sign */

static inline uint64_t exsi_adds_u(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b; return (n == 64 ? t < a : t > exsi_mask(n)) ? exsi_mask(n) : t; }
static inline uint64_t exsi_subs_u(uint64_t a, uint64_t b, unsigned n)
{ (void)n; return a < b ? 0 : a - b; }
static inline uint64_t exsi_adds_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a + b, s = UINT64_C(1) << (n - 1);
  if (n == 64) return ((((a ^ t) & (b ^ t)) >> 63) != 0) ? ((a >> 63) ? s : s - 1) : t;
  return exsi_norm_i(t, n) != t ? ((t >> 63) ? exsi_norm_i(s, n) : s - 1) : t; }
static inline uint64_t exsi_subs_i(uint64_t a, uint64_t b, unsigned n)
{ uint64_t t = a - b, s = UINT64_C(1) << (n - 1);
  if (n == 64) return ((((a ^ b) & (a ^ t)) >> 63) != 0) ? ((a >> 63) ? s : s - 1) : t;
  return exsi_norm_i(t, n) != t ? ((t >> 63) ? exsi_norm_i(s, n) : s - 1) : t; }

/* A count >= the width traps, as spec 5.4 says it must ("traps, as + traps
 * on overflow"); after the check c < n <= 64, so every C shift below is
 * defined. A negative iN count is a huge unsigned and traps, which is what
 * the reference's `jae` does too. */
static inline uint64_t exsi_shl_u(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return exsi_norm_u(a << c, n); }
static inline uint64_t exsi_shl_i(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return exsi_norm_i(a << c, n); }
static inline uint64_t exsi_shr_u(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1); return a >> c; }
/* arithmetic right shift without a signed shift: the sign replicated by a
 * mask. c == 0 is split out because (x << 64) would be a shift by the
 * type's width. */
static inline uint64_t exsi_shr_i(uint64_t a, uint64_t c, unsigned n)
{ if (c >= n) exsrt_abortus(1);
  return c == 0 ? a : (a >> c) | ((0 - (a >> 63)) << (64 - c)); }

/* Byte-at-a-time, with explicit shifts: the emitted text depends on no
 * assumption about the C host's byte order and asserts none (c-backend.md
 * D2). p[i] is an unsigned char promoted to int and converted straight to
 * uint64_t by the | -- a value in 0..255, never operated on as an int. */
static inline uint64_t exsi_ld_be(const unsigned char *p, unsigned k)
{ uint64_t v = 0; unsigned i; for (i = 0; i < k; i++) v = (v << 8) | p[i]; return v; }
static inline uint64_t exsi_ld_le(const unsigned char *p, unsigned k)
{ uint64_t v = 0; unsigned i; for (i = 0; i < k; i++) v |= (uint64_t)p[i] << (8 * i); return v; }
static inline void exsi_st_be(unsigned char *p, unsigned k, uint64_t v)
{ unsigned i; for (i = 0; i < k; i++) p[i] = (unsigned char)(v >> (8 * (k - 1 - i))); }
static inline void exsi_st_le(unsigned char *p, unsigned k, uint64_t v)
{ unsigned i; for (i = 0; i < k; i++) p[i] = (unsigned char)(v >> (8 * i)); }
#if __BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__
# define exsi_ld_n exsi_ld_le
# define exsi_st_n exsi_st_le
#elif __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__
# define exsi_ld_n exsi_ld_be
# define exsi_st_n exsi_st_be
#else
# error "exsecutor: unknown __BYTE_ORDER__"
#endif

_Static_assert(sizeof(void *) == 8, "exsecutor: this hospes has 64-bit addresses");

uint64_t exs_admitte_caput(unsigned char *p0, uint64_t p1);
uint64_t exs_dcfs_lege32(unsigned char *p0, uint64_t p1);
uint64_t exs_dcfs_crc(unsigned char *p0, uint64_t p1);
uint64_t exs_admitte_corpus(unsigned char *p0, uint64_t p1);

uint64_t exs_admitte_caput(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    unsigned char *v11;
    uint64_t v12;
    uint64_t v13;
    uint64_t v14;
    uint64_t v15;
    uint64_t v16;
    uint64_t v17;
    unsigned char *v19;
    uint64_t v20;
    uint64_t v21;
    uint64_t v22;
    uint64_t v23;
    uint64_t v24;
    uint64_t v25;
    uint64_t v26;
    unsigned char *v28;
    uint64_t v29;
    uint64_t v30;
    uint64_t v31;
    uint64_t v32;
    uint64_t v33;
    uint64_t v34;
    unsigned char *v36;
    uint64_t v37;
    uint64_t v38;
    uint64_t v39;
    uint64_t v40;
    uint64_t v41;
    uint64_t v42;
    uint64_t v44;
    uint64_t v46;
    uint64_t v47;
    unsigned char *v49;
    uint64_t v50;
    uint64_t v51;
    uint64_t v52;
    uint64_t v54;
    uint64_t v56;
    uint64_t v57;
    unsigned char *v59;
    uint64_t v60;
    uint64_t v61;
    uint64_t v62;
    uint64_t v63;
    uint64_t v64;
    uint64_t v66;
    uint64_t v68;
    uint64_t v69;
    unsigned char *v71;
    uint64_t v72;
    uint64_t v73;
    uint64_t v74;
    uint64_t v75;
    uint64_t v76;
    uint64_t v77;
    unsigned char *v79;
    uint64_t v80;
    uint64_t v81;
    uint64_t v82;
    uint64_t v83;
    uint64_t v84;
    uint64_t v85;
    uint64_t v86;
    unsigned char *v88;
    uint64_t v89;
    uint64_t v90;
    uint64_t v91;
    uint64_t v92;
    uint64_t v93;
    uint64_t v94;
    unsigned char *v96;
    uint64_t v97;
    uint64_t v98;
    uint64_t v99;
    uint64_t v100;
    uint64_t v101;
    uint64_t v102;
    uint64_t v104;
    uint64_t v106;
    uint64_t v107;
    uint64_t v108;
    uint64_t v109;
    uint64_t v111;
    uint64_t v113;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(17);
    v4 = (v2 < v3);
    if (v4) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v6 = UINT64_C(1);
    return v6;
b3:
    v8 = UINT64_C(0);
    v9 = UINT64_C(17);
    if (v8 >= v9) exsrt_abortus(1);
    v11 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v8 * 1);
    v12 = exsi_norm_u(exsi_ld_n(v11 + 0, 1), 8);
    v13 = exsi_norm_u(exsi_norm_u(v12, 8), 32);
    v14 = UINT64_C(24);
    v15 = exsi_shl_u(v13, v14, 32);
    v16 = UINT64_C(1);
    v17 = UINT64_C(17);
    if (v16 >= v17) exsrt_abortus(1);
    v19 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v16 * 1);
    v20 = exsi_norm_u(exsi_ld_n(v19 + 0, 1), 8);
    v21 = exsi_norm_u(exsi_norm_u(v20, 8), 32);
    v22 = UINT64_C(16);
    v23 = exsi_shl_u(v21, v22, 32);
    v24 = v15 | v23;
    v25 = UINT64_C(2);
    v26 = UINT64_C(17);
    if (v25 >= v26) exsrt_abortus(1);
    v28 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v25 * 1);
    v29 = exsi_norm_u(exsi_ld_n(v28 + 0, 1), 8);
    v30 = exsi_norm_u(exsi_norm_u(v29, 8), 32);
    v31 = UINT64_C(8);
    v32 = exsi_shl_u(v30, v31, 32);
    v33 = UINT64_C(3);
    v34 = UINT64_C(17);
    if (v33 >= v34) exsrt_abortus(1);
    v36 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v33 * 1);
    v37 = exsi_norm_u(exsi_ld_n(v36 + 0, 1), 8);
    v38 = exsi_norm_u(exsi_norm_u(v37, 8), 32);
    v39 = v32 | v38;
    v40 = v24 | v39;
    v41 = UINT64_C(1145259603);
    v42 = (v40 != v41);
    if (v42) {
        goto b4;
    } else {
        goto b5;
    }
b4:
    v44 = UINT64_C(2);
    return v44;
b5:
    v46 = UINT64_C(4);
    v47 = UINT64_C(17);
    if (v46 >= v47) exsrt_abortus(1);
    v49 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v46 * 1);
    v50 = exsi_norm_u(exsi_ld_n(v49 + 0, 1), 8);
    v51 = UINT64_C(5);
    v52 = (v50 != v51);
    if (v52) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v54 = UINT64_C(3);
    return v54;
b7:
    v56 = UINT64_C(8);
    v57 = UINT64_C(17);
    if (v56 >= v57) exsrt_abortus(1);
    v59 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v56 * 1);
    v60 = exsi_norm_u(exsi_ld_n(v59 + 0, 1), 8);
    v61 = UINT64_C(227);
    v62 = v60 & v61;
    v63 = UINT64_C(0);
    v64 = (v62 != v63);
    if (v64) {
        goto b8;
    } else {
        goto b9;
    }
b8:
    v66 = UINT64_C(4);
    return v66;
b9:
    v68 = UINT64_C(9);
    v69 = UINT64_C(17);
    if (v68 >= v69) exsrt_abortus(1);
    v71 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v68 * 1);
    v72 = exsi_norm_u(exsi_ld_n(v71 + 0, 1), 8);
    v73 = exsi_norm_u(exsi_norm_u(v72, 8), 32);
    v74 = UINT64_C(24);
    v75 = exsi_shl_u(v73, v74, 32);
    v76 = UINT64_C(10);
    v77 = UINT64_C(17);
    if (v76 >= v77) exsrt_abortus(1);
    v79 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v76 * 1);
    v80 = exsi_norm_u(exsi_ld_n(v79 + 0, 1), 8);
    v81 = exsi_norm_u(exsi_norm_u(v80, 8), 32);
    v82 = UINT64_C(16);
    v83 = exsi_shl_u(v81, v82, 32);
    v84 = v75 | v83;
    v85 = UINT64_C(11);
    v86 = UINT64_C(17);
    if (v85 >= v86) exsrt_abortus(1);
    v88 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v85 * 1);
    v89 = exsi_norm_u(exsi_ld_n(v88 + 0, 1), 8);
    v90 = exsi_norm_u(exsi_norm_u(v89, 8), 32);
    v91 = UINT64_C(8);
    v92 = exsi_shl_u(v90, v91, 32);
    v93 = UINT64_C(12);
    v94 = UINT64_C(17);
    if (v93 >= v94) exsrt_abortus(1);
    v96 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v93 * 1);
    v97 = exsi_norm_u(exsi_ld_n(v96 + 0, 1), 8);
    v98 = exsi_norm_u(exsi_norm_u(v97, 8), 32);
    v99 = v92 | v98;
    v100 = v84 | v99;
    v101 = UINT64_C(16777216);
    v102 = (v100 > v101);
    if (v102) {
        goto b10;
    } else {
        goto b11;
    }
b10:
    v104 = UINT64_C(5);
    return v104;
b11:
    v106 = exsi_norm_u(v100, 32);
    v107 = UINT64_C(21);
    v108 = exsi_add_u(v106, v107, 64);
    v109 = (v2 != v108);
    if (v109) {
        goto b12;
    } else {
        goto b13;
    }
b12:
    v111 = UINT64_C(6);
    return v111;
b13:
    v113 = UINT64_C(0);
    return v113;
}

uint64_t exs_dcfs_lege32(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v6;
    uint64_t v8;
    unsigned char *v10;
    uint64_t v11;
    uint64_t v12;
    uint64_t v13;
    uint64_t v14;
    uint64_t v15;
    uint64_t v16;
    uint64_t v17;
    unsigned char *v19;
    uint64_t v20;
    uint64_t v21;
    uint64_t v22;
    uint64_t v23;
    uint64_t v24;
    uint64_t v25;
    uint64_t v26;
    uint64_t v27;
    unsigned char *v29;
    uint64_t v30;
    uint64_t v31;
    uint64_t v32;
    uint64_t v33;
    uint64_t v34;
    uint64_t v35;
    uint64_t v36;
    unsigned char *v38;
    uint64_t v39;
    uint64_t v40;
    uint64_t v41;
    uint64_t v42;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(65553);
    v4 = (v2 > v3);
    if (v4) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v6 = UINT64_C(0);
    return v6;
b3:
    v8 = UINT64_C(65557);
    if (v2 >= v8) exsrt_abortus(1);
    v10 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v2 * 1);
    v11 = exsi_norm_u(exsi_ld_n(v10 + 0, 1), 8);
    v12 = exsi_norm_u(exsi_norm_u(v11, 8), 32);
    v13 = UINT64_C(24);
    v14 = exsi_shl_u(v12, v13, 32);
    v15 = UINT64_C(1);
    v16 = exsi_add_u(v2, v15, 64);
    v17 = UINT64_C(65557);
    if (v16 >= v17) exsrt_abortus(1);
    v19 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v16 * 1);
    v20 = exsi_norm_u(exsi_ld_n(v19 + 0, 1), 8);
    v21 = exsi_norm_u(exsi_norm_u(v20, 8), 32);
    v22 = UINT64_C(16);
    v23 = exsi_shl_u(v21, v22, 32);
    v24 = v14 | v23;
    v25 = UINT64_C(2);
    v26 = exsi_add_u(v2, v25, 64);
    v27 = UINT64_C(65557);
    if (v26 >= v27) exsrt_abortus(1);
    v29 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v26 * 1);
    v30 = exsi_norm_u(exsi_ld_n(v29 + 0, 1), 8);
    v31 = exsi_norm_u(exsi_norm_u(v30, 8), 32);
    v32 = UINT64_C(8);
    v33 = exsi_shl_u(v31, v32, 32);
    v34 = UINT64_C(3);
    v35 = exsi_add_u(v2, v34, 64);
    v36 = UINT64_C(65557);
    if (v35 >= v36) exsrt_abortus(1);
    v38 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v35 * 1);
    v39 = exsi_norm_u(exsi_ld_n(v38 + 0, 1), 8);
    v40 = exsi_norm_u(exsi_norm_u(v39, 8), 32);
    v41 = v33 | v40;
    v42 = v24 | v41;
    return v42;
}

uint64_t exs_dcfs_crc(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    uint64_t v3;
    uint64_t v4;
    uint64_t v6;
    uint64_t v8;
    uint64_t v9;
    uint64_t v11;
    uint64_t v12;
    uint64_t v14;
    uint64_t v15;
    unsigned char *v17;
    uint64_t v18;
    uint64_t v19;
    uint64_t v20;
    uint64_t v21;
    uint64_t v22;
    uint64_t v24;
    uint64_t v25;
    uint64_t v27;
    uint64_t v28;
    uint64_t v29;
    uint64_t v30;
    uint64_t v31;
    uint64_t v32;
    uint64_t v33;
    uint64_t v35;
    uint64_t v36;
    uint64_t v39;
    uint64_t v40;
    uint64_t v42;
    uint64_t v44;
    uint64_t v45;
    uint64_t v47;
    uint64_t v48;
    uint64_t t11;
    uint64_t t14;
    uint64_t t24;
    uint64_t t27;
    uint64_t t42;
    v1 = p0;
    v2 = p1;
    v3 = UINT64_C(65557);
    v4 = (v2 > v3);
    if (v4) {
        goto b2;
    } else {
        goto b3;
    }
b2:
    v6 = UINT64_C(0);
    return v6;
b3:
    v8 = UINT64_C(4294967295);
    v9 = UINT64_C(0);
    t14 = v8;
    t11 = v9;
    v14 = t14;
    v11 = t11;
    goto b4;
b4:
    v12 = (v11 < v2);
    if (v12) {
        goto b5;
    } else {
        goto b6;
    }
b5:
    v15 = UINT64_C(65557);
    if (v11 >= v15) exsrt_abortus(1);
    v17 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v11 * 1);
    v18 = exsi_norm_u(exsi_ld_n(v17 + 0, 1), 8);
    v19 = exsi_norm_u(exsi_norm_u(v18, 8), 32);
    v20 = v14 ^ v19;
    v21 = UINT64_C(0);
    v22 = UINT64_C(8);
    t27 = v20;
    t24 = v21;
    v27 = t27;
    v24 = t24;
    goto b8;
b6:
    v47 = UINT64_C(4294967295);
    v48 = v14 ^ v47;
    return v48;
b7:
    v44 = UINT64_C(1);
    v45 = v11 + v44;
    t14 = v27;
    t11 = v45;
    v14 = t14;
    v11 = t11;
    goto b4;
b8:
    v25 = (v24 < v22);
    if (v25) {
        goto b9;
    } else {
        goto b10;
    }
b9:
    v28 = UINT64_C(1);
    v29 = v27 & v28;
    v30 = UINT64_C(1);
    v31 = exsi_shr_u(v27, v30, 32);
    v32 = UINT64_C(1);
    v33 = (v29 == v32);
    if (v33) {
        goto b12;
    } else {
        t42 = v31;
        v42 = t42;
        goto b13;
    }
b10:
    goto b7;
b11:
    v39 = UINT64_C(1);
    v40 = v24 + v39;
    t27 = v42;
    t24 = v40;
    v27 = t27;
    v24 = t24;
    goto b8;
b12:
    v35 = UINT64_C(3988292384);
    v36 = v31 ^ v35;
    t42 = v36;
    v42 = t42;
    goto b13;
b13:
    goto b11;
}

uint64_t exs_admitte_corpus(unsigned char *p0, uint64_t p1)
{
    unsigned char *v1;
    uint64_t v2;
    unsigned char *v3;
    uint64_t v4;
    uint64_t v5;
    uint64_t v7;
    uint64_t v8;
    uint64_t v9;
    unsigned char *v11;
    uint64_t v13;
    uint64_t v14;
    uint64_t v16;
    uint64_t v17;
    uint64_t v19;
    uint64_t v20;
    uint64_t v22;
    unsigned char *v24;
    uint64_t v25;
    uint64_t v26;
    unsigned char *v28;
    uint64_t v31;
    uint64_t v32;
    uint64_t v34;
    uint64_t v35;
    uint64_t v36;
    uint64_t v39;
    uint64_t v40;
    uint64_t v42;
    uint64_t v44;
    uint64_t v45;
    uint64_t v46;
    uint64_t v47;
    uint64_t v48;
    uint64_t v49;
    uint64_t v50;
    uint64_t v52;
    unsigned char *v54;
    uint64_t v55;
    uint64_t v56;
    uint64_t v58;
    uint64_t v59;
    uint64_t v60;
    unsigned char *v62;
    uint64_t v64;
    uint64_t v65;
    unsigned char *v67;
    uint64_t v68;
    uint64_t v69;
    uint64_t v71;
    uint64_t v72;
    uint64_t v73;
    unsigned char *v75;
    uint64_t v77;
    uint64_t v78;
    uint64_t v80;
    uint64_t v81;
    uint64_t v82;
    uint64_t v83;
    uint64_t v84;
    uint64_t v85;
    uint64_t v86;
    uint64_t v88;
    uint64_t v89;
    uint64_t v91;
    uint64_t v92;
    uint64_t v93;
    uint64_t v95;
    uint64_t v96;
    uint64_t v98;
    uint64_t v101;
    uint64_t v102;
    uint64_t v103;
    unsigned char *v105;
    uint64_t v106;
    uint64_t v107;
    uint64_t v108;
    uint64_t v110;
    uint64_t v111;
    uint64_t v112;
    uint64_t v114;
    uint64_t v116;
    unsigned char *v118;
    uint64_t v119;
    uint64_t v120;
    uint64_t v121;
    uint64_t v122;
    uint64_t v123;
    uint64_t v124;
    uint64_t v125;
    unsigned char *v127;
    uint64_t v128;
    uint64_t v129;
    uint64_t v130;
    uint64_t v131;
    uint64_t v132;
    uint64_t v133;
    unsigned char *v135;
    uint64_t v136;
    uint64_t v137;
    uint64_t v138;
    uint64_t v139;
    uint64_t v140;
    uint64_t v142;
    uint64_t v143;
    uint64_t v145;
    uint64_t v146;
    uint64_t v150;
    uint64_t v151;
    uint64_t v152;
    unsigned char *v154;
    uint64_t v155;
    uint64_t v156;
    uint64_t v157;
    uint64_t v159;
    uint64_t v160;
    uint64_t v162;
    uint64_t v163;
    uint64_t v164;
    unsigned char *v166;
    uint64_t v167;
    uint64_t v168;
    uint64_t v169;
    uint64_t v170;
    uint64_t v171;
    uint64_t v172;
    unsigned char *v174;
    uint64_t v178;
    uint64_t v179;
    uint64_t v180;
    uint64_t v182;
    uint64_t v184;
    unsigned char *v186;
    uint64_t v187;
    uint64_t v188;
    uint64_t v189;
    uint64_t v190;
    uint64_t v191;
    uint64_t v192;
    uint64_t v193;
    uint64_t v195;
    uint64_t v197;
    uint64_t v198;
    uint64_t v200;
    uint64_t v201;
    uint64_t v203;
    uint64_t v204;
    uint64_t v207;
    uint64_t v208;
    uint64_t v210;
    uint64_t v211;
    uint64_t v213;
    uint64_t v214;
    uint64_t v217;
    uint64_t v218;
    uint64_t v220;
    uint64_t v221;
    uint64_t v223;
    uint64_t v224;
    uint64_t v227;
    uint64_t v228;
    uint64_t v230;
    uint64_t v231;
    uint64_t v233;
    uint64_t v234;
    uint64_t v236;
    uint64_t v237;
    uint64_t v239;
    uint64_t v240;
    uint64_t v243;
    uint64_t v244;
    uint64_t v246;
    uint64_t v247;
    uint64_t v249;
    uint64_t v250;
    uint64_t v252;
    uint64_t v253;
    uint64_t v255;
    uint64_t v256;
    uint64_t v259;
    uint64_t v260;
    uint64_t v262;
    uint64_t v263;
    uint64_t v265;
    uint64_t v266;
    uint64_t v267;
    uint64_t v268;
    uint64_t v269;
    uint64_t v270;
    uint64_t v271;
    uint64_t v272;
    uint64_t v273;
    uint64_t v274;
    uint64_t v275;
    uint64_t v276;
    uint64_t v277;
    uint64_t v278;
    uint64_t v279;
    uint64_t v280;
    uint64_t v282;
    uint64_t v283;
    uint64_t v284;
    uint64_t v285;
    uint64_t v286;
    uint64_t v287;
    uint64_t v288;
    uint64_t v289;
    uint64_t v290;
    uint64_t v291;
    uint64_t v292;
    uint64_t v293;
    uint64_t v294;
    uint64_t v295;
    uint64_t v296;
    uint64_t v298;
    uint64_t v300;
    uint64_t v302;
    uint64_t v303;
    uint64_t v305;
    uint64_t v306;
    uint64_t v307;
    uint64_t v308;
    uint64_t v309;
    uint64_t v310;
    uint64_t v312;
    uint64_t v313;
    uint64_t v315;
    uint64_t v316;
    uint64_t v317;
    uint64_t v319;
    uint64_t v320;
    uint64_t v322;
    uint64_t v324;
    unsigned char *v326;
    uint64_t v327;
    uint64_t v328;
    uint64_t v329;
    uint64_t v330;
    uint64_t v331;
    uint64_t v332;
    uint64_t v333;
    uint64_t v334;
    uint64_t v336;
    uint64_t v337;
    uint64_t v339;
    uint64_t v342;
    uint64_t v343;
    uint64_t v344;
    uint64_t v345;
    uint64_t v347;
    uint64_t v351;
    uint64_t v352;
    uint64_t v354;
    uint64_t v355;
    uint64_t v356;
    uint64_t v357;
    uint64_t v358;
    uint64_t v359;
    uint64_t v360;
    uint64_t v362;
    uint64_t v364;
    uint64_t v365;
    uint64_t v367;
    uint64_t v368;
    uint64_t v369;
    uint64_t v370;
    uint64_t v372;
    uint64_t v376;
    uint64_t v377;
    uint64_t v379;
    uint64_t v380;
    uint64_t v382;
    uint64_t v383;
    uint64_t v384;
    uint64_t v385;
    uint64_t v386;
    uint64_t v388;
    uint64_t v390;
    uint64_t v391;
    uint64_t v392;
    uint64_t v393;
    uint64_t v394;
    uint64_t v396;
    uint64_t v397;
    uint64_t v399;
    uint64_t v402;
    uint64_t v403;
    uint64_t v404;
    uint64_t v406;
    uint64_t v408;
    uint64_t v409;
    uint64_t v411;
    uint64_t v412;
    uint64_t v413;
    uint64_t v414;
    uint64_t v416;
    uint64_t v417;
    uint64_t v419;
    uint64_t v420;
    unsigned char *v422;
    uint64_t v423;
    uint64_t v424;
    uint64_t v425;
    uint64_t v426;
    uint64_t v428;
    uint64_t v429;
    uint64_t v431;
    uint64_t v432;
    uint64_t v434;
    uint64_t v436;
    uint64_t v437;
    uint64_t v439;
    uint64_t v441;
    uint64_t v442;
    uint64_t v443;
    uint64_t v444;
    uint64_t v446;
    uint64_t v448;
    uint64_t v449;
    uint64_t v451;
    uint64_t v452;
    uint64_t v454;
    uint64_t v457;
    uint64_t v458;
    uint64_t v460;
    uint64_t v462;
    uint64_t v463;
    uint64_t v465;
    uint64_t v467;
    uint64_t v468;
    uint64_t v470;
    uint64_t v472;
    uint64_t v473;
    uint64_t v475;
    uint64_t v477;
    uint64_t v478;
    uint64_t v480;
    uint64_t v484;
    uint64_t v485;
    uint64_t v487;
    uint64_t v489;
    uint64_t v490;
    uint64_t v492;
    uint64_t v494;
    uint64_t v495;
    uint64_t v496;
    uint64_t v497;
    uint64_t v500;
    uint64_t v501;
    uint64_t v503;
    uint64_t v504;
    uint64_t v505;
    uint64_t v506;
    uint64_t v507;
    uint64_t v508;
    uint64_t v509;
    uint64_t v510;
    uint64_t v511;
    uint64_t v512;
    uint64_t v513;
    uint64_t v514;
    uint64_t v515;
    uint64_t v516;
    uint64_t v517;
    uint64_t v518;
    uint64_t v520;
    uint64_t v523;
    uint64_t v526;
    uint64_t v527;
    uint64_t v529;
    uint64_t v530;
    uint64_t v531;
    uint64_t v532;
    uint64_t v533;
    uint64_t v534;
    uint64_t v536;
    uint64_t v538;
    uint64_t v539;
    uint64_t v540;
    uint64_t v541;
    uint64_t v542;
    uint64_t v543;
    uint64_t v544;
    uint64_t v546;
    uint64_t v548;
    uint64_t v549;
    uint64_t v550;
    uint64_t v552;
    uint64_t v554;
    uint64_t v555;
    uint64_t v557;
    uint64_t v559;
    uint64_t v560;
    unsigned char *v562;
    uint64_t v564;
    unsigned char *v566;
    uint64_t v568;
    uint64_t v569;
    uint64_t v571;
    uint64_t v572;
    uint64_t v574;
    uint64_t v575;
    uint64_t v576;
    uint64_t v577;
    uint64_t v578;
    uint64_t v580;
    uint64_t v582;
    uint64_t v583;
    uint64_t v584;
    uint64_t v585;
    uint64_t v586;
    uint64_t v587;
    uint64_t v588;
    uint64_t v590;
    uint64_t v592;
    uint64_t v593;
    uint64_t v594;
    uint64_t v595;
    uint64_t v596;
    uint64_t v598;
    uint64_t v600;
    uint64_t v601;
    uint64_t v602;
    uint64_t v604;
    uint64_t v606;
    uint64_t v607;
    unsigned char *v609;
    uint64_t v611;
    unsigned char *v613;
    uint64_t v615;
    uint64_t v616;
    uint64_t v618;
    uint64_t v619;
    uint64_t v621;
    uint64_t v622;
    uint64_t v623;
    uint64_t v624;
    uint64_t v625;
    uint64_t v627;
    uint64_t v629;
    uint64_t v630;
    uint64_t v631;
    uint64_t v632;
    uint64_t v633;
    uint64_t v635;
    uint64_t v637;
    uint64_t v638;
    unsigned char *v640;
    uint64_t v642;
    uint64_t v643;
    unsigned char *v645;
    uint64_t v647;
    uint64_t v648;
    uint64_t v650;
    uint64_t v651;
    uint64_t v652;
    uint64_t v653;
    uint64_t v654;
    uint64_t v655;
    uint64_t v656;
    uint64_t v657;
    uint64_t v659;
    uint64_t v662;
    uint64_t v663;
    uint64_t v665;
    uint64_t v666;
    uint64_t v667;
    uint64_t v668;
    uint64_t v669;
    uint64_t t7;
    uint64_t t19;
    uint64_t t58;
    uint64_t t71;
    uint64_t t88;
    uint64_t t91;
    uint64_t t95;
    uint64_t t178;
    uint64_t t179;
    uint64_t t265;
    uint64_t t266;
    uint64_t t267;
    uint64_t t268;
    uint64_t t269;
    uint64_t t270;
    uint64_t t271;
    uint64_t t272;
    uint64_t t273;
    uint64_t t274;
    uint64_t t275;
    uint64_t t276;
    uint64_t t277;
    uint64_t t278;
    uint64_t t283;
    uint64_t t284;
    uint64_t t285;
    uint64_t t286;
    uint64_t t287;
    uint64_t t288;
    uint64_t t289;
    uint64_t t290;
    uint64_t t291;
    uint64_t t292;
    uint64_t t293;
    uint64_t t294;
    uint64_t t295;
    uint64_t t312;
    uint64_t t315;
    uint64_t t319;
    uint64_t t330;
    uint64_t t354;
    uint64_t t355;
    uint64_t t356;
    uint64_t t357;
    uint64_t t358;
    uint64_t t367;
    uint64_t t368;
    uint64_t t383;
    uint64_t t416;
    uint64_t t424;
    uint64_t t484;
    uint64_t t489;
    uint64_t t503;
    uint64_t t504;
    uint64_t t505;
    uint64_t t506;
    uint64_t t507;
    uint64_t t508;
    uint64_t t509;
    uint64_t t510;
    uint64_t t511;
    uint64_t t512;
    uint64_t t513;
    uint64_t t514;
    uint64_t t515;
    uint64_t t516;
    uint64_t t530;
    uint64_t t531;
    uint64_t t575;
    uint64_t t600;
    uint64_t t622;
    uint64_t t631;
    uint64_t t650;
    uint64_t t651;
    uint64_t t652;
    uint64_t t653;
    uint64_t t654;
    uint64_t t655;
    uint64_t t665;
    uint64_t t666;
    uint64_t t667;
    uint64_t t668;
    _Alignas(1) unsigned char s3[17];
    _Alignas(1) unsigned char s54[33];
    _Alignas(4) unsigned char s67[132];
    v1 = p0;
    v2 = p1;
    v3 = s3;
    v4 = UINT64_C(0);
    v5 = UINT64_C(0);
    t7 = v5;
    v7 = t7;
    goto b2;
b2:
    v8 = UINT64_C(17);
    v9 = (v7 < v8);
    if (v9) {
        goto b3;
    } else {
        goto b4;
    }
b3:
    v11 = (unsigned char *)((uintptr_t)v3 + (uintptr_t)v7 * 1);
    exsi_st_n(v11 + 0, 1, v4);
    v13 = UINT64_C(1);
    v14 = v7 + v13;
    t7 = v14;
    v7 = t7;
    goto b2;
b4:
    v16 = UINT64_C(0);
    v17 = UINT64_C(17);
    t19 = v16;
    v19 = t19;
    goto b5;
b5:
    v20 = (v19 < v17);
    if (v20) {
        goto b6;
    } else {
        goto b7;
    }
b6:
    v22 = UINT64_C(65557);
    if (v19 >= v22) exsrt_abortus(1);
    v24 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v19 * 1);
    v25 = exsi_norm_u(exsi_ld_n(v24 + 0, 1), 8);
    v26 = UINT64_C(17);
    if (v19 >= v26) exsrt_abortus(1);
    v28 = (unsigned char *)((uintptr_t)v3 + (uintptr_t)v19 * 1);
    exsi_st_n(v28 + 0, 1, v25);
    goto b8;
b7:
    v34 = exs_admitte_caput(v3, v2);
    v35 = UINT64_C(0);
    v36 = (v34 != v35);
    if (v36) {
        goto b9;
    } else {
        goto b10;
    }
b8:
    v31 = UINT64_C(1);
    v32 = v19 + v31;
    t19 = v32;
    v19 = t19;
    goto b5;
b9:
    return v34;
b10:
    v39 = UINT64_C(65557);
    v40 = (v2 > v39);
    if (v40) {
        goto b11;
    } else {
        goto b12;
    }
b11:
    v42 = UINT64_C(7);
    return v42;
b12:
    v44 = UINT64_C(21);
    v45 = exsi_sub_u(v2, v44, 64);
    v46 = UINT64_C(17);
    v47 = exsi_add_u(v46, v45, 64);
    v48 = exs_dcfs_crc(v1, v47);
    v49 = exs_dcfs_lege32(v1, v47);
    v50 = (v48 != v49);
    if (v50) {
        goto b13;
    } else {
        goto b14;
    }
b13:
    v52 = UINT64_C(8);
    return v52;
b14:
    v54 = s54;
    v55 = UINT64_C(0);
    v56 = UINT64_C(0);
    t58 = v56;
    v58 = t58;
    goto b15;
b15:
    v59 = UINT64_C(33);
    v60 = (v58 < v59);
    if (v60) {
        goto b16;
    } else {
        goto b17;
    }
b16:
    v62 = (unsigned char *)((uintptr_t)v54 + (uintptr_t)v58 * 1);
    exsi_st_n(v62 + 0, 1, v55);
    v64 = UINT64_C(1);
    v65 = v58 + v64;
    t58 = v65;
    v58 = t58;
    goto b15;
b17:
    v67 = s67;
    v68 = UINT64_C(0);
    v69 = UINT64_C(0);
    t71 = v69;
    v71 = t71;
    goto b18;
b18:
    v72 = UINT64_C(33);
    v73 = (v71 < v72);
    if (v73) {
        goto b19;
    } else {
        goto b20;
    }
b19:
    v75 = (unsigned char *)((uintptr_t)v67 + (uintptr_t)v71 * 4);
    exsi_st_n(v75 + 0, 4, v68);
    v77 = UINT64_C(1);
    v78 = v71 + v77;
    t71 = v78;
    v71 = t71;
    goto b18;
b20:
    v80 = UINT64_C(0);
    v81 = UINT64_C(17);
    v82 = UINT64_C(2);
    v83 = exsi_mul_u(v45, v82, 64);
    v84 = UINT64_C(2);
    v85 = exsi_add_u(v83, v84, 64);
    v86 = UINT64_C(0);
    t95 = v81;
    t91 = v80;
    t88 = v86;
    v95 = t95;
    v91 = t91;
    v88 = t88;
    goto b21;
b21:
    v89 = (v88 < v85);
    if (v89) {
        goto b22;
    } else {
        goto b23;
    }
b22:
    v92 = UINT64_C(0);
    v93 = (v91 == v92);
    if (v93) {
        goto b25;
    } else {
        goto b26;
    }
b23:
    v669 = UINT64_C(99);
    return v669;
b24:
    v662 = UINT64_C(1);
    v663 = v88 + v662;
    t95 = v667;
    t91 = v665;
    t88 = v663;
    v95 = t95;
    v91 = t91;
    v88 = t88;
    goto b21;
b25:
    v96 = (v95 == v47);
    if (v96) {
        goto b27;
    } else {
        goto b28;
    }
b26:
    v101 = UINT64_C(1);
    v102 = exsi_sub_u(v91, v101, 64);
    v103 = UINT64_C(33);
    if (v102 >= v103) exsrt_abortus(1);
    v105 = (unsigned char *)((uintptr_t)v54 + (uintptr_t)v102 * 1);
    v106 = exsi_norm_u(exsi_ld_n(v105 + 0, 1), 8);
    v107 = UINT64_C(2);
    v108 = (v106 == v107);
    if (v108) {
        goto b30;
    } else {
        goto b31;
    }
b27:
    v98 = UINT64_C(0);
    return v98;
b28:
    t178 = v95;
    v178 = t178;
    goto b29;
b29:
    v180 = (v178 >= v47);
    if (v180) {
        goto b41;
    } else {
        goto b42;
    }
b30:
    v110 = exsi_sub_u(v47, v95, 64);
    v111 = UINT64_C(3);
    v112 = (v110 < v111);
    if (v112) {
        goto b32;
    } else {
        goto b33;
    }
b31:
    v150 = UINT64_C(1);
    v151 = exsi_sub_u(v91, v150, 64);
    v152 = UINT64_C(33);
    if (v151 >= v152) exsrt_abortus(1);
    v154 = (unsigned char *)((uintptr_t)v67 + (uintptr_t)v151 * 4);
    v155 = exsi_norm_u(exsi_ld_n(v154 + 0, 4), 32);
    v156 = UINT64_C(0);
    v157 = (v155 == v156);
    if (v157) {
        goto b39;
    } else {
        goto b40;
    }
b32:
    v114 = UINT64_C(10);
    return v114;
b33:
    v116 = UINT64_C(65557);
    if (v95 >= v116) exsrt_abortus(1);
    v118 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v95 * 1);
    v119 = exsi_norm_u(exsi_ld_n(v118 + 0, 1), 8);
    v120 = exsi_norm_u(exsi_norm_u(v119, 8), 16);
    v121 = UINT64_C(8);
    v122 = exsi_shl_u(v120, v121, 16);
    v123 = UINT64_C(1);
    v124 = exsi_add_u(v95, v123, 64);
    v125 = UINT64_C(65557);
    if (v124 >= v125) exsrt_abortus(1);
    v127 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v124 * 1);
    v128 = exsi_norm_u(exsi_ld_n(v127 + 0, 1), 8);
    v129 = exsi_norm_u(exsi_norm_u(v128, 8), 16);
    v130 = v122 | v129;
    v131 = UINT64_C(2);
    v132 = exsi_add_u(v95, v131, 64);
    v133 = UINT64_C(65557);
    if (v132 >= v133) exsrt_abortus(1);
    v135 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v132 * 1);
    v136 = exsi_norm_u(exsi_ld_n(v135 + 0, 1), 8);
    v137 = UINT64_C(3);
    v138 = exsi_add_u(v95, v137, 64);
    v139 = UINT64_C(0);
    v140 = (v130 == v139);
    if (v140) {
        goto b34;
    } else {
        goto b35;
    }
b34:
    v142 = UINT64_C(0);
    v143 = (v136 == v142);
    if (v143) {
        goto b36;
    } else {
        goto b37;
    }
b35:
    t179 = v138;
    v179 = t179;
    goto b38;
b36:
    v145 = UINT64_C(1);
    v146 = exsi_sub_u(v91, v145, 64);
    t667 = v138;
    t665 = v146;
    v667 = t667;
    v665 = t665;
    goto b24;
b37:
    goto b35;
b38:
    t178 = v179;
    v178 = t178;
    goto b29;
b39:
    v159 = UINT64_C(1);
    v160 = exsi_sub_u(v91, v159, 64);
    t667 = v95;
    t665 = v160;
    v667 = t667;
    v665 = t665;
    goto b24;
b40:
    v162 = UINT64_C(1);
    v163 = exsi_sub_u(v91, v162, 64);
    v164 = UINT64_C(33);
    if (v163 >= v164) exsrt_abortus(1);
    v166 = (unsigned char *)((uintptr_t)v67 + (uintptr_t)v163 * 4);
    v167 = exsi_norm_u(exsi_ld_n(v166 + 0, 4), 32);
    v168 = UINT64_C(1);
    v169 = exsi_sub_u(v167, v168, 32);
    v170 = UINT64_C(1);
    v171 = exsi_sub_u(v91, v170, 64);
    v172 = UINT64_C(33);
    if (v171 >= v172) exsrt_abortus(1);
    v174 = (unsigned char *)((uintptr_t)v67 + (uintptr_t)v171 * 4);
    exsi_st_n(v174 + 0, 4, v169);
    t179 = v95;
    v179 = t179;
    goto b38;
b41:
    v182 = UINT64_C(10);
    return v182;
b42:
    v184 = UINT64_C(65557);
    if (v178 >= v184) exsrt_abortus(1);
    v186 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v178 * 1);
    v187 = exsi_norm_u(exsi_ld_n(v186 + 0, 1), 8);
    v188 = UINT64_C(1);
    v189 = exsi_add_u(v178, v188, 64);
    v190 = UINT64_C(0);
    v191 = UINT64_C(0);
    v192 = UINT64_C(0);
    v193 = (v187 == v192);
    if (v193) {
        goto b43;
    } else {
        t273 = v191;
        v273 = t273;
        goto b44;
    }
b43:
    v195 = UINT64_C(1);
    t273 = v195;
    v273 = t273;
    goto b44;
b44:
    v197 = UINT64_C(1);
    v198 = (v187 >= v197);
    if (v198) {
        goto b45;
    } else {
        t290 = v190;
        t272 = v273;
        v290 = t290;
        v272 = t272;
        goto b46;
    }
b45:
    v200 = UINT64_C(3);
    v201 = (v187 <= v200);
    if (v201) {
        goto b47;
    } else {
        t291 = v190;
        t274 = v273;
        v291 = t291;
        v274 = t274;
        goto b48;
    }
b46:
    v207 = UINT64_C(4);
    v208 = (v187 >= v207);
    if (v208) {
        goto b49;
    } else {
        t289 = v290;
        t271 = v272;
        v289 = t289;
        v271 = t271;
        goto b50;
    }
b47:
    v203 = UINT64_C(1);
    v204 = UINT64_C(1);
    t291 = v204;
    t274 = v203;
    v291 = t291;
    v274 = t274;
    goto b48;
b48:
    t290 = v291;
    t272 = v274;
    v290 = t290;
    v272 = t272;
    goto b46;
b49:
    v210 = UINT64_C(5);
    v211 = (v187 <= v210);
    if (v211) {
        goto b51;
    } else {
        t292 = v290;
        t275 = v272;
        v292 = t292;
        v275 = t275;
        goto b52;
    }
b50:
    v217 = UINT64_C(6);
    v218 = (v187 >= v217);
    if (v218) {
        goto b53;
    } else {
        t288 = v289;
        t270 = v271;
        v288 = t288;
        v270 = t270;
        goto b54;
    }
b51:
    v213 = UINT64_C(1);
    v214 = UINT64_C(2);
    t292 = v214;
    t275 = v213;
    v292 = t292;
    v275 = t275;
    goto b52;
b52:
    t289 = v292;
    t271 = v275;
    v289 = t289;
    v271 = t271;
    goto b50;
b53:
    v220 = UINT64_C(7);
    v221 = (v187 <= v220);
    if (v221) {
        goto b55;
    } else {
        t293 = v289;
        t276 = v271;
        v293 = t293;
        v276 = t276;
        goto b56;
    }
b54:
    v227 = UINT64_C(10);
    v228 = (v187 == v227);
    if (v228) {
        goto b57;
    } else {
        t287 = v288;
        t269 = v270;
        v287 = t287;
        v269 = t269;
        goto b58;
    }
b55:
    v223 = UINT64_C(1);
    v224 = UINT64_C(4);
    t293 = v224;
    t276 = v223;
    v293 = t293;
    v276 = t276;
    goto b56;
b56:
    t288 = v293;
    t270 = v276;
    v288 = t288;
    v270 = t270;
    goto b54;
b57:
    v230 = UINT64_C(1);
    v231 = UINT64_C(4);
    t287 = v231;
    t269 = v230;
    v287 = t287;
    v269 = t269;
    goto b58;
b58:
    v233 = UINT64_C(8);
    v234 = (v187 >= v233);
    if (v234) {
        goto b59;
    } else {
        t286 = v287;
        t268 = v269;
        v286 = t286;
        v268 = t268;
        goto b60;
    }
b59:
    v236 = UINT64_C(9);
    v237 = (v187 <= v236);
    if (v237) {
        goto b61;
    } else {
        t294 = v287;
        t277 = v269;
        v294 = t294;
        v277 = t277;
        goto b62;
    }
b60:
    v243 = UINT64_C(11);
    v244 = (v187 == v243);
    if (v244) {
        goto b63;
    } else {
        t285 = v286;
        t267 = v268;
        v285 = t285;
        v267 = t267;
        goto b64;
    }
b61:
    v239 = UINT64_C(1);
    v240 = UINT64_C(8);
    t294 = v240;
    t277 = v239;
    v294 = t294;
    v277 = t277;
    goto b62;
b62:
    t286 = v294;
    t268 = v277;
    v286 = t286;
    v268 = t268;
    goto b60;
b63:
    v246 = UINT64_C(1);
    v247 = UINT64_C(8);
    t285 = v247;
    t267 = v246;
    v285 = t285;
    v267 = t267;
    goto b64;
b64:
    v249 = UINT64_C(48);
    v250 = (v187 >= v249);
    if (v250) {
        goto b65;
    } else {
        t284 = v285;
        t266 = v267;
        v284 = t284;
        v266 = t266;
        goto b66;
    }
b65:
    v252 = UINT64_C(49);
    v253 = (v187 <= v252);
    if (v253) {
        goto b67;
    } else {
        t295 = v285;
        t278 = v267;
        v295 = t295;
        v278 = t278;
        goto b68;
    }
b66:
    v259 = UINT64_C(19);
    v260 = (v187 == v259);
    if (v260) {
        goto b69;
    } else {
        t283 = v284;
        t265 = v266;
        v283 = t283;
        v265 = t265;
        goto b70;
    }
b67:
    v255 = UINT64_C(1);
    v256 = UINT64_C(8);
    t295 = v256;
    t278 = v255;
    v295 = t295;
    v278 = t278;
    goto b68;
b68:
    t284 = v295;
    t266 = v278;
    v284 = t284;
    v266 = t266;
    goto b66;
b69:
    v262 = UINT64_C(1);
    v263 = UINT64_C(16);
    t283 = v263;
    t265 = v262;
    v283 = t283;
    v265 = t265;
    goto b70;
b70:
    v279 = UINT64_C(1);
    v280 = (v265 == v279);
    if (v280) {
        goto b71;
    } else {
        t356 = v189;
        v356 = t356;
        goto b72;
    }
b71:
    v282 = exsi_sub_u(v47, v189, 64);
    v296 = (v282 < v283);
    if (v296) {
        goto b73;
    } else {
        goto b74;
    }
b72:
    v302 = UINT64_C(16);
    v303 = (v187 == v302);
    if (v303) {
        goto b75;
    } else {
        t654 = v265;
        t383 = v356;
        v654 = t654;
        v383 = t383;
        goto b76;
    }
b73:
    v298 = UINT64_C(10);
    return v298;
b74:
    v300 = exsi_add_u(v189, v283, 64);
    t356 = v300;
    v356 = t356;
    goto b72;
b75:
    v305 = UINT64_C(1);
    v306 = UINT64_C(0);
    v307 = UINT64_C(0);
    v308 = UINT64_C(0);
    v309 = UINT64_C(0);
    v310 = UINT64_C(10);
    t367 = v307;
    t330 = v306;
    t319 = v356;
    t315 = v308;
    t312 = v309;
    v367 = t367;
    v330 = t330;
    v319 = t319;
    v315 = t315;
    v312 = t312;
    goto b77;
b76:
    v376 = UINT64_C(17);
    v377 = (v187 >= v376);
    if (v377) {
        goto b97;
    } else {
        t653 = v654;
        t530 = v383;
        v653 = t653;
        v530 = t530;
        goto b98;
    }
b77:
    v313 = (v312 < v310);
    if (v313) {
        goto b78;
    } else {
        goto b79;
    }
b78:
    v316 = UINT64_C(0);
    v317 = (v315 == v316);
    if (v317) {
        goto b81;
    } else {
        t368 = v367;
        t358 = v330;
        t357 = v319;
        t354 = v315;
        v368 = t368;
        v358 = t358;
        v357 = t357;
        v354 = t354;
        goto b82;
    }
b79:
    v359 = UINT64_C(0);
    v360 = (v315 == v359);
    if (v360) {
        goto b91;
    } else {
        goto b92;
    }
b80:
    v351 = UINT64_C(1);
    v352 = v312 + v351;
    t367 = v368;
    t330 = v358;
    t319 = v357;
    t315 = v354;
    t312 = v352;
    v367 = t367;
    v330 = t330;
    v319 = t319;
    v315 = t315;
    v312 = t312;
    goto b77;
b81:
    v320 = (v319 >= v47);
    if (v320) {
        goto b83;
    } else {
        goto b84;
    }
b82:
    goto b80;
b83:
    v322 = UINT64_C(10);
    return v322;
b84:
    v324 = UINT64_C(65557);
    if (v319 >= v324) exsrt_abortus(1);
    v326 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v319 * 1);
    v327 = exsi_norm_u(exsi_ld_n(v326 + 0, 1), 8);
    v328 = UINT64_C(1);
    v329 = exsi_add_u(v319, v328, 64);
    v331 = UINT64_C(1);
    v332 = exsi_add_u(v330, v331, 8);
    v333 = UINT64_C(10);
    v334 = (v332 == v333);
    if (v334) {
        goto b85;
    } else {
        goto b86;
    }
b85:
    v336 = UINT64_C(1);
    v337 = (v327 > v336);
    if (v337) {
        goto b87;
    } else {
        goto b88;
    }
b86:
    v342 = UINT64_C(128);
    v343 = v327 & v342;
    v344 = UINT64_C(0);
    v345 = (v343 == v344);
    if (v345) {
        goto b89;
    } else {
        t355 = v315;
        v355 = t355;
        goto b90;
    }
b87:
    v339 = UINT64_C(15);
    return v339;
b88:
    goto b86;
b89:
    v347 = UINT64_C(1);
    t355 = v347;
    v355 = t355;
    goto b90;
b90:
    t368 = v327;
    t358 = v332;
    t357 = v329;
    t354 = v355;
    v368 = t368;
    v358 = t358;
    v357 = t357;
    v354 = t354;
    goto b82;
b91:
    v362 = UINT64_C(15);
    return v362;
b92:
    v364 = UINT64_C(2);
    v365 = (v330 >= v364);
    if (v365) {
        goto b93;
    } else {
        goto b94;
    }
b93:
    v369 = UINT64_C(0);
    v370 = (v367 == v369);
    if (v370) {
        goto b95;
    } else {
        goto b96;
    }
b94:
    t654 = v305;
    t383 = v319;
    v654 = t654;
    v383 = t383;
    goto b76;
b95:
    v372 = UINT64_C(15);
    return v372;
b96:
    goto b94;
b97:
    v379 = UINT64_C(18);
    v380 = (v187 <= v379);
    if (v380) {
        goto b99;
    } else {
        t655 = v654;
        t531 = v383;
        v655 = t655;
        v531 = t531;
        goto b100;
    }
b98:
    v526 = UINT64_C(32);
    v527 = (v187 == v526);
    if (v527) {
        goto b146;
    } else {
        t652 = v653;
        t600 = v91;
        t575 = v530;
        v652 = t652;
        v600 = t600;
        v575 = t575;
        goto b147;
    }
b99:
    v382 = UINT64_C(1);
    v384 = exsi_sub_u(v47, v383, 64);
    v385 = UINT64_C(4);
    v386 = (v384 < v385);
    if (v386) {
        goto b101;
    } else {
        goto b102;
    }
b100:
    t653 = v655;
    t530 = v531;
    v653 = t653;
    v530 = t530;
    goto b98;
b101:
    v388 = UINT64_C(10);
    return v388;
b102:
    v390 = exs_dcfs_lege32(v1, v383);
    v391 = UINT64_C(4);
    v392 = exsi_add_u(v383, v391, 64);
    v393 = UINT64_C(17);
    v394 = (v187 == v393);
    if (v394) {
        goto b103;
    } else {
        goto b104;
    }
b103:
    v396 = UINT64_C(65536);
    v397 = (v390 > v396);
    if (v397) {
        goto b105;
    } else {
        goto b106;
    }
b104:
    v402 = exsi_norm_u(v390, 32);
    v403 = exsi_sub_u(v47, v392, 64);
    v404 = (v402 > v403);
    if (v404) {
        goto b107;
    } else {
        goto b108;
    }
b105:
    v399 = UINT64_C(13);
    return v399;
b106:
    goto b104;
b107:
    v406 = UINT64_C(10);
    return v406;
b108:
    v408 = UINT64_C(17);
    v409 = (v187 == v408);
    if (v409) {
        goto b109;
    } else {
        goto b110;
    }
b109:
    v411 = UINT64_C(0);
    v412 = UINT64_C(128);
    v413 = UINT64_C(191);
    v414 = UINT64_C(0);
    t489 = v413;
    t484 = v412;
    t424 = v411;
    t416 = v414;
    v489 = t489;
    v484 = t484;
    v424 = t424;
    v416 = t416;
    goto b111;
b110:
    v523 = exsi_add_u(v392, v402, 64);
    t655 = v382;
    t531 = v523;
    v655 = t655;
    v531 = t531;
    goto b100;
b111:
    v417 = (v416 < v402);
    if (v417) {
        goto b112;
    } else {
        goto b113;
    }
b112:
    v419 = exsi_add_u(v392, v416, 64);
    v420 = UINT64_C(65557);
    if (v419 >= v420) exsrt_abortus(1);
    v422 = (unsigned char *)((uintptr_t)v1 + (uintptr_t)v419 * 1);
    v423 = exsi_norm_u(exsi_ld_n(v422 + 0, 1), 8);
    v425 = UINT64_C(0);
    v426 = (v424 == v425);
    if (v426) {
        goto b115;
    } else {
        goto b116;
    }
b113:
    v517 = UINT64_C(0);
    v518 = (v424 != v517);
    if (v518) {
        goto b144;
    } else {
        goto b145;
    }
b114:
    v500 = UINT64_C(1);
    v501 = v416 + v500;
    t489 = v513;
    t484 = v509;
    t424 = v503;
    t416 = v501;
    v489 = t489;
    v484 = t484;
    v424 = t424;
    v416 = t416;
    goto b111;
b115:
    v428 = UINT64_C(128);
    v429 = (v423 >= v428);
    if (v429) {
        goto b117;
    } else {
        t514 = v489;
        t510 = v484;
        t504 = v424;
        v514 = t514;
        v510 = t510;
        v504 = t504;
        goto b118;
    }
b116:
    v485 = (v423 < v484);
    if (v485) {
        goto b140;
    } else {
        goto b141;
    }
b117:
    v431 = UINT64_C(194);
    v432 = (v423 < v431);
    if (v432) {
        goto b119;
    } else {
        goto b120;
    }
b118:
    t513 = v514;
    t509 = v510;
    t503 = v504;
    v513 = t513;
    v509 = t509;
    v503 = t503;
    goto b139;
b119:
    v434 = UINT64_C(14);
    return v434;
b120:
    v436 = UINT64_C(245);
    v437 = (v423 >= v436);
    if (v437) {
        goto b121;
    } else {
        goto b122;
    }
b121:
    v439 = UINT64_C(14);
    return v439;
b122:
    v441 = UINT64_C(128);
    v442 = UINT64_C(191);
    v443 = UINT64_C(223);
    v444 = (v423 <= v443);
    if (v444) {
        goto b123;
    } else {
        t507 = v424;
        v507 = t507;
        goto b124;
    }
b123:
    v446 = UINT64_C(1);
    t507 = v446;
    v507 = t507;
    goto b124;
b124:
    v448 = UINT64_C(224);
    v449 = (v423 >= v448);
    if (v449) {
        goto b125;
    } else {
        t506 = v507;
        v506 = t506;
        goto b126;
    }
b125:
    v451 = UINT64_C(239);
    v452 = (v423 <= v451);
    if (v452) {
        goto b127;
    } else {
        t508 = v507;
        v508 = t508;
        goto b128;
    }
b126:
    v457 = UINT64_C(240);
    v458 = (v423 >= v457);
    if (v458) {
        goto b129;
    } else {
        t505 = v506;
        v505 = t505;
        goto b130;
    }
b127:
    v454 = UINT64_C(2);
    t508 = v454;
    v508 = t508;
    goto b128;
b128:
    t506 = v508;
    v506 = t506;
    goto b126;
b129:
    v460 = UINT64_C(3);
    t505 = v460;
    v505 = t505;
    goto b130;
b130:
    v462 = UINT64_C(224);
    v463 = (v423 == v462);
    if (v463) {
        goto b131;
    } else {
        t512 = v441;
        v512 = t512;
        goto b132;
    }
b131:
    v465 = UINT64_C(160);
    t512 = v465;
    v512 = t512;
    goto b132;
b132:
    v467 = UINT64_C(237);
    v468 = (v423 == v467);
    if (v468) {
        goto b133;
    } else {
        t516 = v442;
        v516 = t516;
        goto b134;
    }
b133:
    v470 = UINT64_C(159);
    t516 = v470;
    v516 = t516;
    goto b134;
b134:
    v472 = UINT64_C(240);
    v473 = (v423 == v472);
    if (v473) {
        goto b135;
    } else {
        t511 = v512;
        v511 = t511;
        goto b136;
    }
b135:
    v475 = UINT64_C(144);
    t511 = v475;
    v511 = t511;
    goto b136;
b136:
    v477 = UINT64_C(244);
    v478 = (v423 == v477);
    if (v478) {
        goto b137;
    } else {
        t515 = v516;
        v515 = t515;
        goto b138;
    }
b137:
    v480 = UINT64_C(143);
    t515 = v480;
    v515 = t515;
    goto b138;
b138:
    t514 = v515;
    t510 = v511;
    t504 = v505;
    v514 = t514;
    v510 = t510;
    v504 = t504;
    goto b118;
b139:
    goto b114;
b140:
    v487 = UINT64_C(14);
    return v487;
b141:
    v490 = (v423 > v489);
    if (v490) {
        goto b142;
    } else {
        goto b143;
    }
b142:
    v492 = UINT64_C(14);
    return v492;
b143:
    v494 = UINT64_C(1);
    v495 = exsi_sub_u(v424, v494, 8);
    v496 = UINT64_C(128);
    v497 = UINT64_C(191);
    t513 = v497;
    t509 = v496;
    t503 = v495;
    v513 = t513;
    v509 = t509;
    v503 = t503;
    goto b139;
b144:
    v520 = UINT64_C(14);
    return v520;
b145:
    goto b110;
b146:
    v529 = UINT64_C(1);
    v532 = exsi_sub_u(v47, v530, 64);
    v533 = UINT64_C(5);
    v534 = (v532 < v533);
    if (v534) {
        goto b148;
    } else {
        goto b149;
    }
b147:
    v571 = UINT64_C(33);
    v572 = (v187 == v571);
    if (v572) {
        goto b156;
    } else {
        t651 = v652;
        t631 = v600;
        t622 = v575;
        v651 = t651;
        v631 = t631;
        v622 = t622;
        goto b157;
    }
b148:
    v536 = UINT64_C(10);
    return v536;
b149:
    v538 = UINT64_C(1);
    v539 = exsi_add_u(v530, v538, 64);
    v540 = exs_dcfs_lege32(v1, v539);
    v541 = UINT64_C(5);
    v542 = exsi_add_u(v530, v541, 64);
    v543 = UINT64_C(1048576);
    v544 = (v540 > v543);
    if (v544) {
        goto b150;
    } else {
        goto b151;
    }
b150:
    v546 = UINT64_C(12);
    return v546;
b151:
    v548 = exsi_norm_u(v540, 32);
    v549 = exsi_sub_u(v47, v542, 64);
    v550 = (v548 > v549);
    if (v550) {
        goto b152;
    } else {
        goto b153;
    }
b152:
    v552 = UINT64_C(12);
    return v552;
b153:
    v554 = UINT64_C(32);
    v555 = (v91 >= v554);
    if (v555) {
        goto b154;
    } else {
        goto b155;
    }
b154:
    v557 = UINT64_C(11);
    return v557;
b155:
    v559 = UINT64_C(1);
    v560 = UINT64_C(33);
    if (v91 >= v560) exsrt_abortus(1);
    v562 = (unsigned char *)((uintptr_t)v54 + (uintptr_t)v91 * 1);
    exsi_st_n(v562 + 0, 1, v559);
    v564 = UINT64_C(33);
    if (v91 >= v564) exsrt_abortus(1);
    v566 = (unsigned char *)((uintptr_t)v67 + (uintptr_t)v91 * 4);
    exsi_st_n(v566 + 0, 4, v540);
    v568 = UINT64_C(1);
    v569 = exsi_add_u(v91, v568, 64);
    t652 = v529;
    t600 = v569;
    t575 = v542;
    v652 = t652;
    v600 = t600;
    v575 = t575;
    goto b147;
b156:
    v574 = UINT64_C(1);
    v576 = exsi_sub_u(v47, v575, 64);
    v577 = UINT64_C(6);
    v578 = (v576 < v577);
    if (v578) {
        goto b158;
    } else {
        goto b159;
    }
b157:
    v618 = UINT64_C(34);
    v619 = (v187 == v618);
    if (v619) {
        goto b166;
    } else {
        t668 = v622;
        t666 = v631;
        t650 = v651;
        v668 = t668;
        v666 = t666;
        v650 = t650;
        goto b167;
    }
b158:
    v580 = UINT64_C(10);
    return v580;
b159:
    v582 = UINT64_C(2);
    v583 = exsi_add_u(v575, v582, 64);
    v584 = exs_dcfs_lege32(v1, v583);
    v585 = UINT64_C(6);
    v586 = exsi_add_u(v575, v585, 64);
    v587 = UINT64_C(1048576);
    v588 = (v584 > v587);
    if (v588) {
        goto b160;
    } else {
        goto b161;
    }
b160:
    v590 = UINT64_C(12);
    return v590;
b161:
    v592 = UINT64_C(2);
    v593 = exsi_mul_u(v584, v592, 32);
    v594 = exsi_norm_u(v593, 32);
    v595 = exsi_sub_u(v47, v586, 64);
    v596 = (v594 > v595);
    if (v596) {
        goto b162;
    } else {
        goto b163;
    }
b162:
    v598 = UINT64_C(12);
    return v598;
b163:
    v601 = UINT64_C(32);
    v602 = (v600 >= v601);
    if (v602) {
        goto b164;
    } else {
        goto b165;
    }
b164:
    v604 = UINT64_C(11);
    return v604;
b165:
    v606 = UINT64_C(1);
    v607 = UINT64_C(33);
    if (v600 >= v607) exsrt_abortus(1);
    v609 = (unsigned char *)((uintptr_t)v54 + (uintptr_t)v600 * 1);
    exsi_st_n(v609 + 0, 1, v606);
    v611 = UINT64_C(33);
    if (v600 >= v611) exsrt_abortus(1);
    v613 = (unsigned char *)((uintptr_t)v67 + (uintptr_t)v600 * 4);
    exsi_st_n(v613 + 0, 4, v593);
    v615 = UINT64_C(1);
    v616 = exsi_add_u(v600, v615, 64);
    t651 = v574;
    t631 = v616;
    t622 = v586;
    v651 = t651;
    v631 = t631;
    v622 = t622;
    goto b157;
b166:
    v621 = UINT64_C(1);
    v623 = exsi_sub_u(v47, v622, 64);
    v624 = UINT64_C(2);
    v625 = (v623 < v624);
    if (v625) {
        goto b168;
    } else {
        goto b169;
    }
b167:
    v656 = UINT64_C(0);
    v657 = (v650 == v656);
    if (v657) {
        goto b172;
    } else {
        goto b173;
    }
b168:
    v627 = UINT64_C(10);
    return v627;
b169:
    v629 = UINT64_C(2);
    v630 = exsi_add_u(v622, v629, 64);
    v632 = UINT64_C(32);
    v633 = (v631 >= v632);
    if (v633) {
        goto b170;
    } else {
        goto b171;
    }
b170:
    v635 = UINT64_C(11);
    return v635;
b171:
    v637 = UINT64_C(2);
    v638 = UINT64_C(33);
    if (v631 >= v638) exsrt_abortus(1);
    v640 = (unsigned char *)((uintptr_t)v54 + (uintptr_t)v631 * 1);
    exsi_st_n(v640 + 0, 1, v637);
    v642 = UINT64_C(0);
    v643 = UINT64_C(33);
    if (v631 >= v643) exsrt_abortus(1);
    v645 = (unsigned char *)((uintptr_t)v67 + (uintptr_t)v631 * 4);
    exsi_st_n(v645 + 0, 4, v642);
    v647 = UINT64_C(1);
    v648 = exsi_add_u(v631, v647, 64);
    t668 = v630;
    t666 = v648;
    t650 = v621;
    v668 = t668;
    v666 = t666;
    v650 = t650;
    goto b167;
b172:
    v659 = UINT64_C(9);
    return v659;
b173:
    t667 = v668;
    t665 = v666;
    v667 = t667;
    v665 = t665;
    goto b24;
}

